### ISSUE TITLE
启动首页的时候Swiper一下轮播了好多次

### ISSUE THREAD

**Issue by shortybin** [seasonZhu/GetXStudy#2]
把首页的 Swiper 属性 autoplay 定义到 HomeController，默认为 false, 请求到 banner 数据后再设置为 true

**Comment by seasonZhu** [comment]
非常抱歉，最近忙工作的事情，都没有注意看这个项目的issue，感谢意见，目前已经修改了。
本来上周就准备改了，结果生病了。
