### ISSUE TITLE
json实体类生成用的哪个插件？

### ISSUE THREAD

**Issue by yuzepeng** [seasonZhu/GetXStudy#3]
如题，使用了《FlutterJsonBeanFactory》插件生成了新的实体类，结果影响了已有的 而且格式还不一致 求作者同款插件

**Comment by seasonZhu** [comment]
我就是使用的FlutterJsonBeanFactory，只是手动做了部分不够优雅的处理，比如涉及BaseEntity，PageEntity，泛型中套用泛型的情况，都是我自己处理的。

**Comment by yuzepeng** [comment]
> 我就是使用的FlutterJsonBeanFactory，只是手动做了部分不够优雅的处理，比如涉及BaseEntity，PageEntity，泛型中套用泛型的情况，都是我自己处理的。

 明白了 十分感谢  这个项目对于刚转flutter的开发者来说 学习和练手十分友好

**Comment by seasonZhu** [comment]
感谢厚爱，最近忙，都没怎么更新了，谢谢支持。
